/**
 * 开店星新零售管理系统
 * @description 基于Yii2+Vue2.0+uniapp研发，H5+小程序+公众号全渠道覆盖，功能完善开箱即用，框架成熟易扩展二开
 * @author 青岛开店星信息技术有限公司
 * @link https://www.kaidianxing.com
 * @copyright Copyright (c) 2020-2022 Qingdao ShopStar Information Technology Co., Ltd.
 * @copyright 版权归青岛开店星信息技术有限公司所有
 * @warning Unauthorized deletion of copyright information is prohibited.
 * @warning 未经许可禁止私自删除版权信息.
 */ 
/****
 * articlePoster
 * 文章海报默认模板数据
 *
 * */

const articlePoster = [
	{
		id: 'poster_bgimg',
		type: 'poster_bgimg',
		name: '背景图片',
		max: 1,
		isfixed: 1,
		params: {
			imgurl:
				'/static/images/poster/template_1/d886df93b9a37669c7c9071a824b9006.png',
			imgscaletype: 0,
			bgtype: 0,
			draggable: false,
			resizable: false,
		},
		style: {
			zIndex: 0,
			bgcolor: '#FFFFFF',
			width: '100%',
			top: 0,
			left: 0,
			height: '100%',
		},
		data: [],
		_comIndex_: 'poster_bgimg_0_1591691406442',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
		svg: 'tupianzhanbo',
	},
	{
		id: 'poster_articletitle',
		type: 'poster_articletitle',
		name: '文章标题',
		isfixed: 1,
		params: {
			content: '',
			imgscaletype: 1,
		},
		style: {
			textalign: 'left',
			fontsize: '32',
			fontweight: 700,
			color: '#000000',
			top: 772,
			left: 48,
			width: 656,
			height: 88,
			lineheight: 1.43,
		},
		data: [],
		_comIndex_: 'poster_goodname_3_1592544579686',
		svg: 'fuwenben',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
	},
	{
		id: 'poster_articledigest',
		type: 'poster_articledigest',
		name: '文章标题',
		isfixed: 1,
		params: {
			content: '',
			imgscaletype: 1,
		},
		style: {
			textalign: 'left',
			fontsize: '32',
			fontweight: 300,
			color: '#000000',
			top: 882,
			left: 48,
			width: 656,
			height: 88,
			lineheight: 1.43,
		},
		data: [],
		_comIndex_: 'poster_goodname_3_1592544579686',
		svg: 'fuwenben',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
	},
	{
		id: 'poster_qrcode',
		type: 'poster_qrcode',
		name: '二维码',
		isfixed: 1,
		params: { imgurl: '', imgscaletype: 0, bordershow: 1 },
		style: {
			bgcolor: '#ffffff',
			bgopacity: '1',
			width: 200,
			height: 200,
			top: 1070,
			left: '48',
			borderradius: 0,
			color: '#000000',
			bordercolor: '#000000',
			borderwidth: 1,
		},
		data: [],
		_comIndex_: 'poster_qrcode_7_1592880123609',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
		icon: 'iconfont icon-fenxiao-erweima',
	},
	{
		id: 'poster_shopname',
		type: 'poster_shopname',
		name: '店铺昵称',
		isfixed: 1,
		params: { content: '', imgscaletype: 1 },
		style: {
			textalign: 'left',
			fontsize: 28,
			fontweight: 400,
			color: '#000000',
			top: 48,
			left: 340,
			width: 234,
			height: 40,
			lineheight: 1.4,
		},
		data: [],
		_comIndex_: 'poster_shopname_8_1592880295805',
		icon: 'iconfont icon-haibao-dianpumingcheng',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
	},
	{
		id: 'poster_text',
		type: 'poster_text',
		name: '文本',
		isfixed: 1,
		params: { content: '长按二维码进行阅读文章', imgscaletype: 1 },
		style: {
			textalign: 'left',
			fontsize: 28,
			fontweight: 400,
			color: '#969696',
			top: '1124',
			left: '274',
			width: 400,
			height: 40,
			lineheight: 1.6,
		},
		data: [],
		_comIndex_: 'poster_text_8_1592880415829',
		icon: 'iconfont icon-biaotilan',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
	},
	{
		id: 'poster_text',
		type: 'poster_text',
		name: '文本',
		isfixed: 1,
		params: { content: '分享自', imgscaletype: 1 },
		style: {
			textalign: 'left',
			fontsize: 28,
			fontweight: 400,
			color: '#969696',
			top: 1176,
			left: 274,
			width: 90,
			height: 40,
			lineheight: 1.6,
		},
		data: [],
		_comIndex_: 'poster_text_9_1592880437335',
		icon: 'iconfont icon-biaotilan',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
	},
	{
		id: 'poster_img',
		type: 'poster_img',
		name: '商品图片',
		isfixed: 1,
		params: { imgurl: '', imgscaletype: 0, bordershow: 1, borderradius: 0 },
		style: {
			width: 702,
			height: 702,
			top: '40',
			left: 24,
			borderradius: 0,
			bordercolor: '#e6e7eb',
			borderwidth: 1,
		},
		data: [],
		_comIndex_: 'poster_goodimg_9_1592881101963',
		icon: 'iconfont icon-shangpinzu',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
	},
	{
		id: 'poster_shopname',
		type: 'poster_shopname',
		name: '店铺昵称',
		isfixed: 1,
		params: { content: '这里是准生产环境', imgscaletype: 1 },
		style: {
			textalign: 'left',
			fontsize: 28,
			fontweight: 400,
			color: '#969696',
			top: 1178,
			left: '360',
			width: 282,
			height: 40,
			lineheight: 1.4,
		},
		data: [],
		_comIndex_: 'poster_shopname_10_1594006717268',
		icon: 'iconfont icon-haibao-dianpumingcheng',
		groupName: '基础组件',
		yIndex: 2,
		groupType: '2',
		color: '#2D8CF0',
	},
];
export { articlePoster };
