/**
 * groupsPoster
 *
 * 拼团海报数据模板
 *
 * **/

const groupsPoster = [
    {
        "id":"poster_bgimg",
        "type":"poster_bgimg",
        "name":"背景图片",
        "max":1,
        "isfixed":1,
        "params":{
            "imgurl":"",
            "imgscaletype":0,
            "bgtype":1,
            "draggable":false,
            "resizable":false
        },
        "style":{
            "zIndex":0,
            "bgcolor":"#FFFFFF",
            "width":"100%",
            "top":0,
            "left":0,
            "height":"100%"
        },
        "data":[

        ],
        "_comIndex_":"poster_bgimg_0_1591691406442",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2D8CF0",
        "svg":"tupianzhanbo"
    },
    {
        "id":"poster_goodimg",
        "type":"poster_goodimg",
        "name":"商品图片",
        "isfixed":1,
        "params":{
            "imgurl":"",
            "imgscaletype":0,
            "bordershow":0,
            "borderradius":0
        },
        "style":{
            "width":"536",
            "height":536,
            "top":"232",
            "left":"108",
            "borderradius":0,
            "bordercolor":"#e6e7eb",
            "borderwidth":1
        },
        "data":[

        ],
        "_comIndex_":"poster_goodimg_9_1592881101963",
        "icon":"iconfont icon-shangpinzu",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2D8CF0"
    },
    {
        "id":"poster_avatar",
        "type":"poster_avatar",
        "name":"头像",
        "isfixed":1,
        "params":{
            "imgurl":"",
            "imgscaletype":0,
            "bordershow":1,
            'borderradius':0
        },
        "style":{
            "width":"96",
            "height":"96",
            "top":"72",
            "left":"76",
            "borderradius":0,
            "bordercolor":"#ffffff",
            "borderwidth":2
        },
        "data":[

        ],
        "_comIndex_":"poster_avatar_2_1609136381411",
        "icon":"iconfont icon-shuju-huiyuanshu",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_nickname",
        "type":"poster_nickname",
        "name":"昵称",
        "isfixed":1,
        "params":{
            "content":"张三",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":28,
            "fontweight":700,
            "color":"#FFF",
            "top":"76",
            "left":"190",
            "width":210,
            "height":40,
            "lineheight":1.4
        },
        "data":[

        ],
        "_comIndex_":"poster_nickname_3_1609136405331",
        "icon":"iconfont icon-haibao-yonghunicheng",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_text",
        "type":"poster_text",
        "name":"文本",
        "isfixed":1,
        "params":{
            "content":"我发现一件好货，来一起参与拼团吧~",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":28,
            "fontweight":400,
            "color":"#FFFFFF",
            "top":124,
            "left":190,
            "width":508,
            "height":40,
            "lineheight":1.6
        },
        "data":[

        ],
        "_comIndex_":"poster_text_4_1609136448244",
        "icon":"iconfont icon-biaotilan",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_img",
        "type":"poster_img",
        "name":"图片",
        "isfixed":1,
        "params":{
            "imgurl":"image/172/2020/12/28d035f9993872d6067cc9cfac09f9ba.png",
            "imgscaletype":0,
            "bordershow":0,
            "borderradius":1
        },
        "style":{
            "width":"56",
            "height":32,
            "top":796,
            "left":"108",
            "bordercolor":"#e6e7eb",
            "borderwidth":1
        },
        "data":[

        ],
        "_comIndex_":"poster_img_13_1609210339235",
        "icon":"iconfont icon-datuzu",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0",
        "svg":"tupianzhanbo"
    },
    {
        "id":"poster_text",
        "type":"poster_text",
        "name":"文本",
        "isfixed":1,
        "params":{
            "content":"拼团",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":"20",
            "fontweight":700,
            "color":"#FFF",
            "top":"798",
            "left":"115",
            "width":48,
            "height":40,
            "lineheight":1.6
        },
        "data":[

        ],
        "_comIndex_":"poster_text_14_1609210507087",
        "icon":"iconfont icon-biaotilan",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_goodname",
        "type":"poster_goodname",
        "name":"商品名称",
        "isfixed":1,
        "params":{
            "content":"",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":"32",
            "fontweight":700,
            "color":"#212121",
            "top":792,
            "left":108,
            "width":540,
            "height":88,
            "lineheight":1.43
        },
        "data":[

        ],
        "_comIndex_":"poster_goodname_5_1609136477827",
        "svg":"fuwenben",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_text",
        "type":"poster_text",
        "name":"文本",
        "isfixed":1,
        "params":{
            "content":"拼团价",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":"36",
            "fontweight":700,
            "color":"#FF3C29",
            "top":906,
            "left":112,
            "width":118,
            "height":58,
            "lineheight":1.6
        },
        "data":[

        ],
        "_comIndex_":"poster_text_6_1609136529747",
        "icon":"iconfont icon-biaotilan",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_price",
        "type":"poster_price",
        "name":"商品现价",
        "isfixed":1,
        "params":{
            "content":"1999.00",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":"44",
            "fontweight":"700",
            "color":"#FF3C29",
            "top":902,
            "left":222,
            "width":384,
            "height":50,
            "lineheight":1
        },
        "data":[

        ],
        "_comIndex_":"poster_price_7_1609136561307",
        "icon":"iconfont icon-haibao-xianjia",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0",
        "svg":"haibao-xianjia"
    },
    {
        "id":"poster_text",
        "type":"poster_text",
        "name":"文本",
        "isfixed":1,
        "params":{
            "content":"单买价",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":"32",
            "fontweight":400,
            "color":"#939799",
            "top":962,
            "left":112,
            "width":116,
            "height":56,
            "lineheight":1.6
        },
        "data":[

        ],
        "_comIndex_":"poster_text_8_1609136587227",
        "icon":"iconfont icon-biaotilan",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_delprice",
        "type":"poster_delprice",
        "name":"商品原价",
        "isfixed":1,
        "params":{
            "content":"1999.00",
            "showdelline":"1",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":"32",
            "fontweight":400,
            "color":"#939799",
            "top":966,
            "left":218,
            "width":256,
            "height":38,
            "lineheight":1
        },
        "data":[

        ],
        "_comIndex_":"poster_delprice_9_1609136628988",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0",
        "svg":"haibao-yuanjia"
    },
    {
        "id":"poster_qrcode",
        "type":"poster_qrcode",
        "name":"二维码",
        "isfixed":1,
        "params":{
            "imgurl":"",
            "imgscaletype":0,
            "bordershow":0,
            "borderradius": 0
        },
        "style":{
            "bgcolor":"#ffffff",
            "bgopacity":"1",
            "width":"170",
            "height":"170",
            "top":"1090",
            "left":"174",
            "borderradius":0,
            "color":"#000000",
            "bordercolor":"#e6e7eb",
            "borderwidth":1
        },
        "data":[

        ],
        "_comIndex_":"poster_qrcode_10_1609136656940",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0",
        "svg":"erweima"
    },
    {
        "id":"poster_text",
        "type":"poster_text",
        "name":"文本",
        "isfixed":1,
        "params":{
            "content":"长按识别二维码",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":28,
            "fontweight":400,
            "color":"#FFFFFF",
            "top":"1124",
            "left":"380",
            "width":210,
            "height":40,
            "lineheight":1.6
        },
        "data":[

        ],
        "_comIndex_":"poster_text_11_1609136703092",
        "icon":"iconfont icon-biaotilan",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    },
    {
        "id":"poster_text",
        "type":"poster_text",
        "name":"文本",
        "isfixed":1,
        "params":{
            "content":"立即参团",
            "imgscaletype":1
        },
        "style":{
            "textalign":"left",
            "fontsize":"36",
            "fontweight":700,
            "color":"#FFFFFF",
            "top":"1172",
            "left":"380",
            "width":210,
            "height":52,
            "lineheight":1.6
        },
        "data":[

        ],
        "_comIndex_":"poster_text_12_1609136722500",
        "icon":"iconfont icon-biaotilan",
        "groupName":"基础组件",
        "yIndex":2,
        "groupType":"2",
        "color":"#2d8cf0"
    }
]

export { groupsPoster }
